# Generated by Django 6.0.6 on 2026-06-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="pokemons/"),
        ),
    ]
